/* eslint-disable prettier/prettier */
/* eslint-disable quotes */
/* eslint-disable prettier/prettier */
export const mockJobPostings = [
    {
      jobType: "Software Engineer",
      companyName: "Tech Company",
      jobText: "Full-stack developer role. Focus on React and Node.js development.",
      location: "San Francisco",
      dateApplied: "2024-09-15T08:00:00Z",
    },
    {
      jobType: "Data Analyst",
      companyName: "Analytics Co.",
      jobText: "Data analysis and reporting role. Working with Python, SQL, and visualization tools.",
      location: "New York",
      dateApplied: "2024-09-13T08:00:00Z",
    },
    {
      jobType: "UX Designer",
      companyName: "Design Co.",
      jobText: "",
      location: "Austin",
      dateApplied: "2024-09-10T08:00:00Z",
    },
    {
      jobType: "Backend Engineer",
      companyName: "API Hub",
      jobText: "Developing and maintaining RESTful APIs for large-scale applications.",
      location: "Chicago",
      dateApplied: "2024-09-12T08:00:00Z",
    },
    {
      jobType: "Project Manager",
      companyName: "Tech Projects",
      jobText: "Managing software projects and ensuring timely delivery.",
      location: "Seattle",
      dateApplied: "2024-09-11T08:00:00Z",
    },
    {
      jobType: "DevOps Engineer",
      companyName: "Cloud Solutions",
      jobText: "Setting up CI/CD pipelines and managing cloud infrastructure.",
      location: "Boston",
      dateApplied: "2024-09-09T08:00:00Z",
    },
    {
      jobType: "Security Analyst",
      companyName: "SecureIT",
      jobText: "Conducting security audits and vulnerability assessments.",
      location: "Los Angeles",
      dateApplied: "2024-09-08T08:00:00Z",
    },
    {
      jobType: "Mobile App Developer",
      companyName: "Appify",
      jobText: "Building cross-platform mobile applications with React Native.",
      location: "San Diego",
      dateApplied: "2024-09-07T08:00:00Z",
    },
    {
      jobType: "Database Administrator",
      companyName: "Data Corp",
      jobText: "Managing databases and ensuring data integrity.",
      location: "Denver",
      dateApplied: "2024-09-06T08:00:00Z",
    },
    {
      jobType: "Product Manager",
      companyName: "Innovate Tech",
      jobText: "Leading product development teams to build scalable products.",
      location: "Miami",
      dateApplied: "2024-09-05T08:00:00Z",
    },
    {
      jobType: "Frontend Developer",
      companyName: "Frontend Masters",
      jobText: "Developing dynamic user interfaces using React and Angular.",
      location: "Dallas",
      dateApplied: "2024-09-04T08:00:00Z",
    },
    {
      jobType: "Data Scientist",
      companyName: "AI Labs",
      jobText: "Applying machine learning models to solve business problems.",
      location: "Palo Alto",
      dateApplied: "2024-09-03T08:00:00Z",
    },
    {
      jobType: "Marketing Manager",
      companyName: "MarketBuzz",
      jobText: "Leading marketing campaigns and strategies for tech products.",
      location: "Phoenix",
      dateApplied: "2024-09-02T08:00:00Z",
    },
    {
      jobType: "Systems Engineer",
      companyName: "Systematics",
      jobText: "Designing and implementing IT systems.",
      location: "San Jose",
      dateApplied: "2024-09-01T08:00:00Z",
    },
    {
      jobType: "Software Tester",
      companyName: "BugFixers",
      jobText: "Ensuring software quality through manual and automated testing.",
      location: "Orlando",
      dateApplied: "2024-08-31T08:00:00Z",
    },
    {
      jobType: "Cloud Engineer",
      companyName: "Cloudify",
      jobText: "Managing and optimizing cloud resources on AWS and Azure.",
      location: "Atlanta",
      dateApplied: "2024-08-30T08:00:00Z",
    },
    {
      jobType: "Business Analyst",
      companyName: "BizAnalyze",
      jobText: "Working with stakeholders to gather and document requirements.",
      location: "Portland",
      dateApplied: "2024-08-29T08:00:00Z",
    },
    {
      jobType: "Data Engineer",
      companyName: "Big Data Solutions",
      jobText: "Building data pipelines and ensuring data quality.",
      location: "Salt Lake City",
      dateApplied: "2024-08-28T08:00:00Z",
    },
    {
      jobType: "Content Writer",
      companyName: "Tech Writers",
      jobText: "Creating content for tech blogs and websites.",
      location: "Tampa",
      dateApplied: "2024-08-27T08:00:00Z",
    },
    {
      jobType: "Network Administrator",
      companyName: "NetSecure",
      jobText: "Managing network infrastructure and security.",
      location: "Charlotte",
      dateApplied: "2024-08-26T08:00:00Z",
    },
    {
      jobType: "Scrum Master",
      companyName: "AgileWorks",
      jobText: "Facilitating agile ceremonies and removing impediments.",
      location: "Minneapolis",
      dateApplied: "2024-08-25T08:00:00Z",
    },
    {
      jobType: "Machine Learning Engineer",
      companyName: "AI Solutions",
      jobText: "Building and deploying machine learning models.",
      location: "Newark",
      dateApplied: "2024-08-24T08:00:00Z",
    },
    {
      jobType: "Graphic Designer",
      companyName: "Design Studios",
      jobText: "Creating visual content for marketing and branding purposes.",
      location: "Sacramento",
      dateApplied: "2024-08-23T08:00:00Z",
    },
    {
      jobType: "IT Support Specialist",
      companyName: "HelpDesk Pro",
      jobText: "Providing IT support and troubleshooting for clients.",
      location: "Las Vegas",
      dateApplied: "2024-08-22T08:00:00Z",
    },
    {
      jobType: "Blockchain Developer",
      companyName: "CryptoTech",
      jobText: "Building decentralized applications using blockchain technology.",
      location: "Austin",
      dateApplied: "2024-08-21T08:00:00Z",
    }
  ];
  